### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by Protektor-Desura** [fHDHR/fHDHR_NewsOn#37]
```
version: '2.1'
services:
  fhdhr_newson:
    image: fhdhr_newson:0.4.6
    container_name: fhdhr_newson
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    ports:
      - 1900:1900
      - 5004:5004
    volumes:
      - /<docker-config-directory>/fhdhr_newson:/app/config
    restart: always
```
